In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 'Cards2.py',
 'SeattleWages.ipynb',
 'Seattle_Wages.csv',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Testing.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb']

In [2]:
import pandas

In [4]:
df1=pandas.read_csv("Seattle_Wages.csv")
df1

,Jobtitle,Female Avg Hrly Rate,No. Female Empl,Average of Female MONTHS LONGEVITY IN CURRENT CLASSIFICATION,Male Avg Hrly Rate,No. Male Empl,Average of Male MONTHS LONGEVITY IN CURRENT CLASSIFICATION,Total Avg Hrly Rate,Total No. Empl,Total Average of MONTHS LONGEVITY IN CURRENT CLASSIFICATION,Ratio of women's hourly rate to men's hourly rate - percentage,Notes
0,Accountant,30.58,23.0,88.96,30.28,7.0,85.71,30.51,30,88.20,101%,NaN
1,"Accountant,Prin",38.75,23.0,59.96,37.64,7.0,7.00,38.49,30,47.60,102.95%,NaN
2,"Accountant,Sr",34.48,23.0,60.61,33.89,6.0,43.67,34.36,29,57.10,101.75%,NaN
3,Act Exec,43.10,4.0,146.00,42.02,7.0,106.29,42.42,11,120.73,102.56%,NaN
4,Actg Tech I,22.56,1.0,156.00,NaN,NaN,NaN,22.56,1,156.00,NaN,no men in title
5,Actg Tech I-BU,22.56,10.0,81.80,22.56,2.0,35.50,22.56,12,74.08,100%,NaN
6,Actg Tech II,23.98,7.0,112.71,24.35,1.0,75.00,24.03,8,108.00,98.49%,NaN
7,Actg Tech II-BU,24.19,74.0,103.23,24.21,18.0,134.50,24.20,92,109.35,99.95%,NaN
8,Actg Tech III,26.64,7.0,51.57,NaN,NaN,NaN,26.64,7,51.57,NaN,no men in title
9,Actg Tech III-BU,26.69,32.0,89.97,26.18,5.0,51.20,26.63,37,84.73,101.96%,NaN
10,Actg Tech II-MC,24.35,2.0,199.50,NaN,NaN,NaN,24.35,2,199.50,NaN,no men in title
11,Actg Tech Supv-BU,28.84,4.0,59.25,NaN,NaN,NaN,28.84,4,59.25,NaN,no men in title
12,Admin Spec I,22.35,15.0,129.40,21.76,2.0,46.00,22.28,17,119.59,102.7%,NaN
13,Admin Spec I-BU,22.43,78.0,121.04,22.43,12.0,91.17,22.43,90,117.06,100.01%,NaN
14,Admin Spec II,24.32,28.0,126.07,23.90,4.0,42.50,24.26,32,115.63,101.73%,NaN
15,Admin Spec II-BU,24.25,140.0,91.78,24.11,18.0,76.50,24.24,158,90.04,100.61%,NaN
16,Admin Spec III,26.10,12.0,78.00,26.26,2.0,94.50,26.12,14,80.36,99.39%,NaN
17,Admin Spec III-BU,25.94,30.0,64.90,25.93,3.0,53.67,25.94,33,63.88,100.03%,NaN
18,Admin Spec III-MC,26.26,1.0,72.00,NaN,NaN,NaN,26.26,1,72.00,NaN,no men in title
19,Admin Spec II-MC,24.35,28.0,129.18,24.35,2.0,129.00,24.35,30,129.17,100%,NaN
20,Admin Spec I-MC,22.56,16.0,145.00,22.56,3.0,123.00,22.56,19,141.53,100%,NaN
21,Admin Staff Anlyst,35.59,40.0,76.95,35.00,3.0,49.00,35.55,43,75.00,101.69%,NaN
22,Admin Staff Asst,30.86,54.0,65.80,30.48,8.0,72.00,30.82,62,66.60,101.26%,NaN
23,Admin Support Asst,20.61,1.0,77.00,NaN,NaN,NaN,20.61,1,77.00,NaN,no men in title
24,Admin Support Asst-BU,20.30,10.0,84.20,20.61,2.0,83.00,20.36,12,84.00,98.52%,NaN
25,Admin Support Asst-MC,NaN,NaN,NaN,20.61,2.0,219.50,20.61,2,219.50,NaN,no women in title
26,Admin Support Supv-BU,27.58,10.0,73.50,27.78,2.0,141.00,27.61,12,84.75,99.28%,NaN
27,Admin Support Supv-MC,27.78,4.0,119.25,27.78,1.0,158.00,27.78,5,127.00,100%,NaN
28,Administrator-Law,48.11,1.0,28.00,NaN,NaN,NaN,48.11,1,28.00,NaN,no men in title
29,Adms Employee,17.11,5.0,115.40,17.11,8.0,102.50,17.11,13,107.46,100%,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
842,"Wtr Meter Repairer,Sr",27.67,1.0,183.00,27.67,2.0,146.50,27.67,3,158.67,100%,NaN
843,Wtr Pipe CC,NaN,NaN,NaN,38.42,2.0,158.00,38.42,2,158.00,NaN,no women in title
844,Wtr Pipe CC-WDM II,NaN,NaN,NaN,38.77,6.0,71.00,38.77,6,71.00,NaN,no women in title
845,Wtr Pipe Wkr,30.18,2.0,193.50,30.18,25.0,95.56,30.18,27,102.81,100%,NaN
846,Wtr Pipe Wkr Sr-WDM II,33.64,4.0,85.00,33.64,27.0,67.15,33.64,31,69.45,100%,NaN
847,"Wtr Pipe Wkr,Sr",NaN,NaN,NaN,32.37,10.0,191.20,32.37,10,191.20,NaN,no women in title
848,Wtr Pipe Wkr-WDM I,30.46,1.0,88.00,29.94,15.0,24.87,29.97,16,28.81,101.75%,NaN
849,Wtr Quality Anlyst,33.69,3.0,117.00,33.69,3.0,125.67,33.69,6,121.33,100%,NaN
850,"Wtr Quality Anlyst,Asst",31.16,2.0,77.50,NaN,NaN,NaN,31.16,2,77.50,NaN,no men in title
851,"Wtr Quality Anlyst,Sr",36.30,2.0,125.50,36.30,1.0,57.00,36.30,3,102.67,100%,NaN
852,"Wtr Quality Anlyst,Supv",39.20,1.0,90.00,39.20,1.0,91.00,39.20,2,90.50,100%,NaN
853,Wtr Quality Engr,44.74,1.0,171.00,NaN,NaN,NaN,44.74,1,171.00,NaN,no men in title
854,"Wtr Quality Engr,Sr",NaN,NaN,NaN,50.69,2.0,85.00,50.69,2,85.00,NaN,no women in title
855,Wtr Syst Op,NaN,NaN,NaN,38.58,5.0,140.00,38.58,5,140.00,NaN,no women in title
856,"Wtr Syst Op,Sr",41.72,1.0,150.00,41.72,1.0,120.00,41.72,2,135.00,100%,NaN
857,Wtr Systs Supv,NaN,NaN,NaN,47.63,2.0,138.00,47.63,2,138.00,NaN,no women in title
858,Wtr Treatment CC,36.30,1.0,173.00,36.30,1.0,164.00,36.30,2,168.50,100%,NaN
859,Wtr Treatment Equip Tech,NaN,NaN,NaN,33.09,1.0,42.00,33.09,1,42.00,NaN,no women in title
860,"Wtr Treatment Op,Sr",NaN,NaN,NaN,31.34,2.0,96.50,31.34,2,96.50,NaN,no women in title
861,Wtr Treatment Op-Asg Relief,NaN,NaN,NaN,29.08,1.0,192.00,29.08,1,192.00,NaN,no women in title
862,Wtr Treatment Op-WDM I,28.22,2.0,88.00,27.52,3.0,61.67,27.80,5,72.20,102.56%,NaN
863,Wtrshed Inspector,NaN,NaN,NaN,30.81,3.0,157.00,30.81,3,157.00,NaN,no women in title
864,"Wtrshed Inspector,Sr",34.94,1.0,124.00,NaN,NaN,NaN,34.94,1,124.00,NaN,no men in title
865,Wtrshed Opns Supv,NaN,NaN,NaN,39.96,1.0,107.00,39.96,1,107.00,NaN,no women in title
866,Wtrshed Resource Spec,NaN,NaN,NaN,36.30,1.0,170.00,36.30,1,170.00,NaN,no women in title
867,Wtrshed Resources Tech,NaN,NaN,NaN,34.45,1.0,73.00,34.45,1,73.00,NaN,no women in title
868,"Wtrworks Maint Spec,Sr-SMU",NaN,NaN,NaN,29.99,2.0,43.00,29.99,2,43.00,NaN,no women in title
869,Wtrworks Maint Spec-SMU,NaN,NaN,NaN,27.65,3.0,47.00,27.65,3,47.00,NaN,no women in title
870,Wtrworks Maint Supv,NaN,NaN,NaN,35.57,1.0,14.00,35.57,1,14.00,NaN,no women in title
871,Grand Total,35.35,3600.0,81.83,39.04,6285.0,78.38,37.70,9885,79.64,90.55%,NaN

In [16]:
df1.iloc[5:500, 1:12]

,Female Avg Hrly Rate,No. Female Empl,Average of Female MONTHS LONGEVITY IN CURRENT CLASSIFICATION,Male Avg Hrly Rate,No. Male Empl,Average of Male MONTHS LONGEVITY IN CURRENT CLASSIFICATION,Total Avg Hrly Rate,Total No. Empl,Total Average of MONTHS LONGEVITY IN CURRENT CLASSIFICATION,Ratio of women's hourly rate to men's hourly rate - percentage,Notes
5,22.56,10.0,81.80,22.56,2.0,35.50,22.56,12,74.08,100%,NaN
6,23.98,7.0,112.71,24.35,1.0,75.00,24.03,8,108.00,98.49%,NaN
7,24.19,74.0,103.23,24.21,18.0,134.50,24.20,92,109.35,99.95%,NaN
8,26.64,7.0,51.57,NaN,NaN,NaN,26.64,7,51.57,NaN,no men in title
9,26.69,32.0,89.97,26.18,5.0,51.20,26.63,37,84.73,101.96%,NaN
10,24.35,2.0,199.50,NaN,NaN,NaN,24.35,2,199.50,NaN,no men in title
11,28.84,4.0,59.25,NaN,NaN,NaN,28.84,4,59.25,NaN,no men in title
12,22.35,15.0,129.40,21.76,2.0,46.00,22.28,17,119.59,102.7%,NaN
13,22.43,78.0,121.04,22.43,12.0,91.17,22.43,90,117.06,100.01%,NaN
14,24.32,28.0,126.07,23.90,4.0,42.50,24.26,32,115.63,101.73%,NaN
15,24.25,140.0,91.78,24.11,18.0,76.50,24.24,158,90.04,100.61%,NaN
16,26.10,12.0,78.00,26.26,2.0,94.50,26.12,14,80.36,99.39%,NaN
17,25.94,30.0,64.90,25.93,3.0,53.67,25.94,33,63.88,100.03%,NaN
18,26.26,1.0,72.00,NaN,NaN,NaN,26.26,1,72.00,NaN,no men in title
19,24.35,28.0,129.18,24.35,2.0,129.00,24.35,30,129.17,100%,NaN
20,22.56,16.0,145.00,22.56,3.0,123.00,22.56,19,141.53,100%,NaN
21,35.59,40.0,76.95,35.00,3.0,49.00,35.55,43,75.00,101.69%,NaN
22,30.86,54.0,65.80,30.48,8.0,72.00,30.82,62,66.60,101.26%,NaN
23,20.61,1.0,77.00,NaN,NaN,NaN,20.61,1,77.00,NaN,no men in title
24,20.30,10.0,84.20,20.61,2.0,83.00,20.36,12,84.00,98.52%,NaN
25,NaN,NaN,NaN,20.61,2.0,219.50,20.61,2,219.50,NaN,no women in title
26,27.58,10.0,73.50,27.78,2.0,141.00,27.61,12,84.75,99.28%,NaN
27,27.78,4.0,119.25,27.78,1.0,158.00,27.78,5,127.00,100%,NaN
28,48.11,1.0,28.00,NaN,NaN,NaN,48.11,1,28.00,NaN,no men in title
29,17.11,5.0,115.40,17.11,8.0,102.50,17.11,13,107.46,100%,NaN
30,NaN,NaN,NaN,24.10,1.0,161.00,24.10,1,161.00,NaN,no women in title
31,24.32,1.0,55.00,24.08,4.0,55.50,24.13,5,55.40,101.01%,NaN
32,26.53,3.0,128.67,26.53,6.0,142.17,26.53,9,137.67,100%,NaN
33,30.72,2.0,54.00,NaN,NaN,NaN,30.72,2,54.00,NaN,no men in title
34,NaN,NaN,NaN,43.91,1.0,54.00,43.91,1,54.00,NaN,no women in title
...,...,...,...,...,...,...,...,...,...,...,...
470,NaN,NaN,NaN,56.20,5.0,31.20,56.20,5,31.20,NaN,no women in title
471,NaN,NaN,NaN,52.00,1.0,1.00,52.00,1,1.00,NaN,no women in title
472,52.69,2.0,46.50,NaN,NaN,NaN,52.69,2,46.50,NaN,no men in title
473,NaN,NaN,NaN,55.65,12.0,95.17,55.65,12,95.17,NaN,no women in title
474,58.24,4.0,38.50,57.91,9.0,66.89,58.01,13,58.15,100.57%,NaN
475,NaN,NaN,NaN,34.32,1.0,24.00,34.32,1,24.00,NaN,no women in title
476,38.85,4.0,39.25,NaN,NaN,NaN,38.85,4,39.25,NaN,no men in title
477,35.14,3.0,8.00,NaN,NaN,NaN,35.14,3,8.00,NaN,no men in title
478,31.16,1.0,160.00,NaN,NaN,NaN,31.16,1,160.00,NaN,no men in title
479,30.16,2.0,8.00,30.16,1.0,8.00,30.16,3,8.00,100%,NaN
480,24.95,1.0,8.00,NaN,NaN,NaN,24.95,1,8.00,NaN,no men in title
481,NaN,NaN,NaN,37.70,1.0,35.00,37.70,1,35.00,NaN,no women in title
482,37.70,1.0,167.00,NaN,NaN,NaN,37.70,1,167.00,NaN,no men in title
483,38.20,1.0,63.00,38.20,1.0,25.00,38.20,2,44.00,100%,NaN
484,33.96,1.0,1.00,33.96,4.0,71.25,33.96,5,57.20,100%,NaN
485,34.13,1.0,89.00,36.09,11.0,78.64,35.93,12,79.50,94.57%,NaN
486,NaN,NaN,NaN,31.05,17.0,61.76,31.05,17,61.76,NaN,no women in title
487,NaN,NaN,NaN,32.02,8.0,56.38,32.02,8,56.38,NaN,no women in title
488,NaN,NaN,NaN,86.11,1.0,40.00,86.11,1,40.00,NaN,no women in title
489,22.73,2.0,2.50,22.74,2.0,8.00,22.73,4,5.25,99.93%,NaN
490,30.07,8.0,36.63,28.60,3.0,39.67,29.67,11,37.45,105.14%,NaN
491,NaN,NaN,NaN,54.66,1.0,157.00,54.66,1,157.00,NaN,no women in title
492,NaN,NaN,NaN,40.86,1.0,382.00,40.86,1,382.00,NaN,no women in title
493,NaN,NaN,NaN,50.69,6.0,115.00,50.69,6,115.00,NaN,no women in title
494,NaN,NaN,NaN,43.91,1.0,124.00,43.91,1,124.00,NaN,no women in title
495,NaN,NaN,NaN,38.81,3.0,80.67,38.81,3,80.67,NaN,no women in title
496,NaN,NaN,NaN,41.55,1.0,6.00,41.55,1,6.00,NaN,no women in title
497,NaN,NaN,NaN,53.39,1.0,7.00,53.39,1,7.00,NaN,no women in title
498,50.07,1.0,43.00,44.80,1.0,7.00,47.44,2,25.00,111.76%,NaN
499,32.54,1.0,244.00,32.54,6.0,175.33,32.54,7,185.14,100%,NaN